@baseUrl = http://localhost:8082

### 1. Healthcheck API (Publik - Tanpa Token)
GET {{baseUrl}}/health
Accept: application/json

### 2. AUTH - Login Dokter (Otomatis Simpan Token)
# @name login
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "DRHANDI",
  "password": "1"
}

### 3. RAWAT JALAN - Uji Coba Tanpa Token (Harus Respon 401 Unauthorized)
POST {{baseUrl}}/api/v1/rawat-jalan/antrean
Content-Type: application/json

{
  "halaman": 1,
  "batas": 10
}

### 4. RAWAT JALAN - Opsi Referensi Filter
GET {{baseUrl}}/api/v1/rawat-jalan/referensi-filter
Authorization: Bearer {{login.response.body.data.token}}
Accept: application/json


### 5. RAWAT JALAN - Daftar Antrean (Otomatis Ambil Token dari Hasil Login)
POST {{baseUrl}}/api/v1/rawat-jalan/antrean
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
  "tanggal": "2026-04-22,2026-04-22",
  "halaman": 1,
  "batas": 50
}

### 5.1 RAWAT JALAN - Uji Coba Multi-Error Validasi Filter (Harus Respon 400 dengan Map Error)
POST {{baseUrl}}/api/v1/rawat-jalan/antrean
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
  "tanggal": "2026-04-22",
  "halaman": 1,
  "batas": 50,
  "order_by": "salah_kolom",
  "sort_order": "SALAH_SORT",
  "jenis_antrean": "AntreanGhoib"
}

### 6. RAWAT JALAN - Detail Kunjungan Pasien (Otomatis Ambil Token dari Hasil Login)
GET {{baseUrl}}/api/v1/rawat-jalan/detail/zEHeUb12ojDNfzppR_shjerisPbYGHnQ97FjZWMXVawwnqQ2_zc_NCDzRBc7
Authorization: Bearer {{login.response.body.data.token}}
Accept: application/json

### 7. PENJAMIN - Daftar Penjamin
GET {{baseUrl}}/api/v1/penjamin
Authorization: Bearer {{login.response.body.data.token}}
Accept: application/json
